##
# PhoneBook

NAME = PhoneBook
CC = c++
FLAGS = -Wall -Wextra -Werror -std=c++98
FILES = main.cpp Contact.cpp PhoneBook.cpp

$(NAME):
	$(CC) $(FLAGS) $(FILES) -o $(NAME)

clean:
	rm -rf $(NAME)

re: clean $(NAME)

# end
